// <auto-generated />
using System;
using GeoSlayer.Domain.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoSlayer.Domain.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917211750_Stage18GameSettings")]
    partial class Stage18GameSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.AdminAuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AdminAuditEntries");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.BankedTransit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BankedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GridLat")
                        .HasColumnType("integer");

                    b.Property<int>("GridLng")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Redeemed")
                        .HasColumnType("boolean");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Redeemed");

                    b.HasIndex("PlayerId", "GridLat", "GridLng")
                        .IsUnique();

                    b.ToTable("BankedTransits");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.CellTerrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClassifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GridLat")
                        .HasColumnType("integer");

                    b.Property<int>("GridLng")
                        .HasColumnType("integer");

                    b.Property<int>("Terrain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GridLat", "GridLng")
                        .IsUnique();

                    b.ToTable("CellTerrains");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentreGridLat")
                        .HasColumnType("integer");

                    b.Property<int>("CentreGridLng")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ClaimedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("TerrainProfile")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "CentreGridLat", "CentreGridLng")
                        .IsUnique();

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ClueStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RiddleText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ScrollId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.Property<double?>("TargetLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("TargetLng")
                        .HasColumnType("double precision");

                    b.Property<int?>("TargetPoiId")
                        .HasColumnType("integer");

                    b.Property<double?>("TargetRadius")
                        .HasColumnType("double precision");

                    b.Property<int?>("TargetSkill")
                        .HasColumnType("integer");

                    b.Property<bool>("WasSkipped")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ScrollId", "StepIndex")
                        .IsUnique();

                    b.ToTable("ClueSteps");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.DistrictDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MinimumClaims")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("OutputBonus")
                        .HasColumnType("double precision");

                    b.Property<int>("RequiredTerrains")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DistrictDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.DropTableEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("Terrain")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("Terrain");

                    b.HasIndex("Terrain", "MaterialId")
                        .IsUnique();

                    b.ToTable("DropTableEntries");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.EncounterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsTrainingGround")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MinCombatLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("EncounterDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.EnvironmentalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnvironmentalSettings");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.GameSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Default")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GameSettings");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.GeoRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CellLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CellLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTime>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegionKey");

                    b.HasIndex("CellLat", "CellLng")
                        .IsUnique();

                    b.ToTable("GeoRegions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ImportedRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CellLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CellLng")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CellLat", "CellLng")
                        .IsUnique();

                    b.ToTable("ImportedRegions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Modifier")
                        .HasColumnType("integer");

                    b.Property<double>("ModifierValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("SecondaryModifier")
                        .HasColumnType("integer");

                    b.Property<double>("SecondaryModifierValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemImages");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseGatherSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("SkillType")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<double>("XpPerUnit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Category", "Tier");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.MuseumEntryDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Wing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Wing");

                    b.ToTable("MuseumEntryDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PatrolRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PatrolRoutes");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PatrolWaypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Sequence")
                        .IsUnique();

                    b.ToTable("PatrolWaypoints");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdventurerLevel")
                        .HasColumnType("integer");

                    b.Property<long>("AdventurerXp")
                        .HasColumnType("bigint");

                    b.Property<int>("BonusPointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("BonusPointsSpent")
                        .HasColumnType("integer");

                    b.Property<long>("Coin")
                        .HasColumnType("bigint");

                    b.Property<long>("CoinDeposited")
                        .HasColumnType("bigint");

                    b.Property<long>("Curation")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InterestSettledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LastCellLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("LastCellLng")
                        .HasColumnType("double precision");

                    b.Property<double>("LastLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("LastLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RespecCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerClueScroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("SkipUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Tier", "CompletedUtc");

                    b.ToTable("PlayerClueScrolls");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerCraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Collected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CompletesUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("PlayerId", "Collected");

                    b.ToTable("PlayerCrafts");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerEncounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SpawnedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("PlayerId", "ResolvedUtc");

                    b.HasIndex("PlayerId", "PoiId", "DefinitionKey")
                        .IsUnique();

                    b.ToTable("PlayerEncounters");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerItems");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PlayerId", "MaterialId")
                        .IsUnique();

                    b.ToTable("PlayerMaterials");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerMuseumEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcquiredAtName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("AcquiredAtPoiId")
                        .HasColumnType("integer");

                    b.Property<int>("DonatedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTime>("FirstAcquiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "EntryKey")
                        .IsUnique();

                    b.ToTable("PlayerMuseumEntries");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerPoiVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstVisitUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastVisitUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("integer");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PoiId");

                    b.HasIndex("PlayerId", "PoiId")
                        .IsUnique();

                    b.ToTable("PlayerPoiVisits");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SkillType")
                        .IsUnique();

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("UpgradeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "UpgradeKey")
                        .IsUnique();

                    b.ToTable("PlayerUpgrades");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OsmId", "OsmType")
                        .IsUnique();

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("OutputItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("OutputMaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<double>("XpReward")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OutputItemId");

                    b.HasIndex("OutputMaterialId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.RecipeInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeId", "MaterialId")
                        .IsUnique();

                    b.ToTable("RecipeInputs");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ResourceSurge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CellLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CellLng")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetSkill")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetTerrain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CellLat", "CellLng", "EndsUtc");

                    b.ToTable("ResourceSurges");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.RevealedCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GridLat")
                        .HasColumnType("integer");

                    b.Property<int>("GridLng")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RevealedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "GridLat", "GridLng")
                        .IsUnique();

                    b.ToTable("RevealedCells");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.SkillDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillType")
                        .IsUnique();

                    b.ToTable("SkillDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.SkillTerrainMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SkillType")
                        .HasColumnType("integer");

                    b.Property<int>("Terrain")
                        .HasColumnType("integer");

                    b.Property<double>("XpPerCell")
                        .HasColumnType("double precision");

                    b.Property<double>("YieldMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SkillType", "Terrain")
                        .IsUnique();

                    b.ToTable("SkillTerrainMappings");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.UnlockDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdventurerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UnlockType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdventurerLevel");

                    b.HasIndex("AdventurerLevel", "Payload")
                        .IsUnique();

                    b.ToTable("UnlockDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.UpgradeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CostCurve")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("EffectPerRank")
                        .HasColumnType("double precision");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxRank")
                        .HasColumnType("integer");

                    b.Property<int>("MinAdventurerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("UpgradeDefinitions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedSkill")
                        .HasColumnType("integer");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastCollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.WorkerExpedition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Collected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DispatchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceMetres")
                        .HasColumnType("double precision");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<string>("PoiName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ReturnsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("PlayerId", "Collected");

                    b.ToTable("WorkerExpeditions");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.BankedTransit", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Claim", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ClueStep", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.PlayerClueScroll", "Scroll")
                        .WithMany("Steps")
                        .HasForeignKey("ScrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scroll");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.DropTableEntry", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.ItemImage", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PatrolRoute", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PatrolWaypoint", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.PatrolRoute", "Route")
                        .WithMany("Waypoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Player", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerClueScroll", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerCraft", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerEncounter", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.PointOfInterest", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerItem", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoSlayer.Domain.Database.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Item");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerMaterial", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerMuseumEntry", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerPoiVisit", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.PointOfInterest", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerSkill", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerUpgrade", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany("Upgrades")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Recipe", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Item", "OutputItem")
                        .WithMany()
                        .HasForeignKey("OutputItemId");

                    b.HasOne("GeoSlayer.Domain.Database.Models.Material", "OutputMaterial")
                        .WithMany()
                        .HasForeignKey("OutputMaterialId");

                    b.Navigation("OutputItem");

                    b.Navigation("OutputMaterial");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.RecipeInput", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.Recipe", "Recipe")
                        .WithMany("Inputs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.RevealedCell", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.UserRefreshToken", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Worker", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.WorkerExpedition", b =>
                {
                    b.HasOne("GeoSlayer.Domain.Database.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.PointOfInterest", "Poi")
                        .WithMany()
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSlayer.Domain.Database.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Poi");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PatrolRoute", b =>
                {
                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Player", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Upgrades");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.PlayerClueScroll", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("GeoSlayer.Domain.Database.Models.Recipe", b =>
                {
                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
